# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

pool:
 name: Custom

variables:
  - group: dev-zen-container-registry
  - name: imageRepository
    value: 'champions-apis'
  - name: LGTM.UploadSnapshot
    value: true,
  - name: dockerfilePath
    value: '$(Build.SourcesDirectory)/Dockerfile'
  - name: tag
    value: '$(Build.BuildId)'

stages:
 - stage: Hosting
   displayName: Microservice Hosting
   jobs:
   - job: BuildMicroservice
     displayName: Build Microservice
     steps:
     - bash: |
        az login --service-principal -u $(azAppId) -p $(azPassword) --tenant $(azTenant)
        az acr login -n zencontainerregistry
        imageTag="$(containerRegistry)/$(imageRepository):$(tag)"
        echo $imageTag
        docker build . -t $(imageRepository):$(tag)
        docker tag $(imageRepository):$(tag) zencontainerregistry.azurecr.io/$(imageRepository):$(tag)
        docker push zencontainerregistry.azurecr.io/$(imageRepository):$(tag)
        docker tag $(imageRepository):$(tag) zencontainerregistry.azurecr.io/$(imageRepository):latest
        docker push zencontainerregistry.azurecr.io/$(imageRepository):latest
        /confcom/create-container.sh confcom $(resourceGroup) $(containerRegistry) $(containerRegistryUsername) $(containerRegistryPassword) champions-deployment $imageTag
